"""Hypothesis: quant_primary_btc_trend_ema_crossover_v1

Generated by agent quant_primary at cycle 3.
Config: {
  "hypothesis_id": "btc_trend_ema_crossover_v1",
  "created_at": "2026-03-12T03:44:20Z",
  "thesis": "BTC dominates the crypto factor structure (0.85-0.96 correlation with all monitored pairs). In a single-factor market, the highest-value strategy is capturing the primary trend of that factor. A dual EMA crossover on BTC/USD 4h captures intermediate trends while filtering noise. Given extreme fear (FGI=18) and declining volatility, the market is coiling for a directional move. This strategy is designed to capture that move in either direction.",
  "strategy_type": "momentum",
  "target_pairs": [
    "BTC/USD"
  ],
  "target_regimes": [
    "trending_bull",
    "trending_bear"
  ],
  "signal_description": "Fast EMA (12 periods = 48h) crosses above slow EMA (26 periods = 104h) \u2192 buy. Fast crosses below slow \u2192 sell/short-close. Position sizing at 30% of capital to manage vol. Hold through trends, only exit on cross or trailing stop at 2x ATR(14).",
  "expected_trade_frequency": "2-4 trades per week based on 4h timeframe EMA crossovers",
  "expected_behavior": "Profitable in trending regimes (captures moves of 3%+), loses in ranging/choppy markets (false crossovers). ATR trailing stop limits downside per trade. In current regime transition, may chop initially but should capture the breakout when it comes.",
  "success_criteria": {
    "metric": "sharpe_ratio",
    "threshold": 0.8,
    "minimum_trade_count": 30,
    "evaluation_window": "90d backtest, then 7d paper minimum",
    "robustness": {
      "random_entry_percentile_min": 70,
      "return_permutation_percentile_min": 60
    },
    "rationale": "Sharpe 0.8 is modest but realistic for a simple trend strategy. 30 minimum trades needed for statistical significance at 4h timeframe over 90d. Random entry percentile at 70 (not 90) because some of the edge is in the trailing stop risk management, not purely entry timing. Permutation at 60 because trend strategies naturally have path-dependent returns."
  },
  "counterfactual_benchmark": {
    "description": "Buy-and-hold BTC over the same period",
    "implementation": "Track BTC/USD return from first signal date to last. Strategy must produce higher risk-adjusted return (Sharpe) than HODL.",
    "null_hypothesis": "If the EMA crossover strategy does not beat buy-and-hold BTC on a Sharpe basis over 90 days with 30+ trades, the entry/exit timing adds no value over passive exposure."
  },
  "failure_modes": [
    "Extended ranging market causes repeated false crossovers and whipsaw losses",
    "Volatility spikes cause ATR stops to be too wide, leading to large single-trade losses",
    "4h timeframe too slow to capture intraday reversals, too fast to capture weekly trends \u2014 stuck in the middle",
    "Transaction costs erode edge on frequent crossovers in choppy markets"
  ]
}
"""

import math
from strategies.base import BaseStrategy, Signal


class BtcTrendEmaCrossoverV1(BaseStrategy):
    """BTC/USD trend-following via dual EMA crossover with ATR trailing stop."""

    def __init__(self, **kwargs):
        self.fast_period = 12  # 48 hours at 4h
        self.slow_period = 26  # 104 hours at 4h
        self.atr_period = 14
        self.atr_stop_mult = 2.0
        self.position_size = 0.30  # 30% of capital
        self.position = 0  # 1 = long, 0 = flat
        self.entry_price = 0.0
        self.trailing_stop = 0.0
        self.highest_since_entry = 0.0

    def name(self) -> str:
        return 'btc_trend_ema_crossover_v1'

    def required_feeds(self) -> list[str]:
        return ['BTC/USD:4h']

    def _ema(self, closes: list, period: int) -> float:
        """Calculate EMA from a list of closing prices."""
        if len(closes) < period:
            return closes[-1] if closes else 0.0
        multiplier = 2.0 / (period + 1)
        ema = sum(closes[:period]) / period  # SMA seed
        for price in closes[period:]:
            ema = (price - ema) * multiplier + ema
        return ema

    def _atr(self, candles: list, period: int) -> float:
        """Calculate ATR from candle dicts."""
        if len(candles) < 2:
            return 0.0
        trs = []
        for i in range(1, len(candles)):
            c = candles[i]
            prev_close = candles[i - 1]['close']
            high = c.get('high', c['close'])
            low = c.get('low', c['close'])
            tr = max(high - low, abs(high - prev_close), abs(low - prev_close))
            trs.append(tr)
        if len(trs) < period:
            return sum(trs) / len(trs) if trs else 0.0
        # Simple average of last 'period' TRs
        return sum(trs[-period:]) / period

    def on_data(self, data: dict) -> list:
        candles = data.get('candles_so_far', [])
        if len(candles) < self.slow_period + 2:
            return []

        closes = [c['close'] for c in candles]
        current_price = closes[-1]

        fast_ema = self._ema(closes, self.fast_period)
        slow_ema = self._ema(closes, self.slow_period)

        # Previous bar EMAs for crossover detection
        prev_closes = closes[:-1]
        prev_fast = self._ema(prev_closes, self.fast_period)
        prev_slow = self._ema(prev_closes, self.slow_period)

        atr = self._atr(candles, self.atr_period)

        signals = []

        if self.position == 1:
            # Update trailing stop
            if current_price > self.highest_since_entry:
                self.highest_since_entry = current_price
                self.trailing_stop = self.highest_since_entry - self.atr_stop_mult * atr

            # Exit conditions: trailing stop hit OR bearish crossover
            bearish_cross = prev_fast >= prev_slow and fast_ema < slow_ema
            stop_hit = current_price <= self.trailing_stop and self.trailing_stop > 0

            if bearish_cross or stop_hit:
                reason = 'bearish_crossover' if bearish_cross else f'trailing_stop_hit_at_{self.trailing_stop:.0f}'
                signals.append(Signal(
                    action='close',
                    pair='BTC/USD',
                    size_pct=1.0,
                    order_type='market',
                    rationale=f'Exit long: {reason}. Entry={self.entry_price:.0f}, Exit={current_price:.0f}, FastEMA={fast_ema:.0f}, SlowEMA={slow_ema:.0f}'
                ))
                self.position = 0
                self.entry_price = 0.0
                self.trailing_stop = 0.0
                self.highest_since_entry = 0.0

        elif self.position == 0:
            # Entry: bullish crossover
            bullish_cross = prev_fast <= prev_slow and fast_ema > slow_ema
            if bullish_cross:
                self.position = 1
                self.entry_price = current_price
                self.highest_since_entry = current_price
                self.trailing_stop = current_price - self.atr_stop_mult * atr
                signals.append(Signal(
                    action='buy',
                    pair='BTC/USD',
                    size_pct=self.position_size,
                    order_type='market',
                    rationale=f'Bullish EMA crossover: Fast({self.fast_period})={fast_ema:.0f} > Slow({self.slow_period})={slow_ema:.0f}. ATR={atr:.0f}, Stop={self.trailing_stop:.0f}'
                ))

        return signals
