"""Dashboard generator for the agentic quant trading system.

Produces a single-file HTML dashboard with inline CSS. Features:
- Executive summary card (generated by Haiku per cycle)
- CSS-only tabbed sections for strategies, research notes, operations
- Cumulative strategy results across lifecycle stages
- Strategy lifecycle funnel, equity curve, agent summaries
"""

import json
from datetime import datetime, timezone
from html import escape

from database.schema import get_db
from logging_config import get_logger

logger = get_logger("dashboard.generator")


def generate_dashboard(
    db_path: str,
    config: dict,
    output_path: str = "dashboard/index.html",
) -> str:
    """Generate a single-file HTML dashboard."""
    conn = get_db(db_path)

    equity_data = _get_equity_data(conn)
    strategies = _get_strategies(conn)
    strategies_by_stage = _get_strategies_by_stage(conn)
    research_notes = _get_research_notes(conn)
    failed_cycles = _get_failed_cycles(conn)
    funnel = _get_strategy_funnel(conn)
    risk_log = _get_risk_log(conn)
    messages = _get_messages(conn)
    feeds = _get_feeds(conn)
    trades = _get_recent_trades(conn)
    system_state = _get_system_state(conn)
    agent_summaries = _get_agent_summaries(conn, config)
    sirs = _get_sirs(conn)
    owner_requests = _get_owner_requests(conn)

    conn.close()

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html = _build_html(
        equity_data=equity_data,
        strategies=strategies,
        strategies_by_stage=strategies_by_stage,
        research_notes=research_notes,
        failed_cycles=failed_cycles,
        funnel=funnel,
        risk_log=risk_log,
        messages=messages,
        feeds=feeds,
        trades=trades,
        system_state=system_state,
        agent_summaries=agent_summaries,
        sirs=sirs,
        owner_requests=owner_requests,
        config=config,
        generated_at=generated_at,
    )

    import os
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    logger.info("Dashboard generated at %s", output_path)
    return output_path


# --------------------------------------------------------------------------
# Data queries
# --------------------------------------------------------------------------

def _get_equity_data(conn) -> list[dict]:
    """Get equity snapshots from events table."""
    rows = conn.execute(
        "SELECT timestamp, payload FROM events "
        "WHERE event_type IN ('cycle_complete', 'equity_snapshot') "
        "ORDER BY timestamp DESC LIMIT 200"
    ).fetchall()
    results = []
    for r in rows:
        try:
            payload = json.loads(r["payload"])
            equity = payload.get("equity") or payload.get("portfolio_value")
            if equity is not None:
                results.append({"timestamp": r["timestamp"], "equity": float(equity)})
        except (json.JSONDecodeError, TypeError):
            pass
    results.reverse()
    return results


def _get_strategies(conn) -> list[dict]:
    """Get all strategies with their current stage."""
    rows = conn.execute(
        "SELECT strategy_id, agent_id, namespace, stage, created_at, updated_at "
        "FROM strategy_registry ORDER BY updated_at DESC"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_strategies_by_stage(conn) -> dict[str, list[dict]]:
    """Get all strategies grouped by stage with parsed JSON result columns."""
    rows = conn.execute(
        "SELECT strategy_id, agent_id, namespace, stage, config, "
        "backtest_results, robustness_results, paper_results, "
        "created_at, updated_at "
        "FROM strategy_registry ORDER BY updated_at DESC"
    ).fetchall()
    by_stage: dict[str, list[dict]] = {}
    for r in rows:
        entry = dict(r)
        for field in ("config", "backtest_results", "robustness_results", "paper_results"):
            if entry.get(field):
                try:
                    entry[field] = json.loads(entry[field])
                except (json.JSONDecodeError, TypeError):
                    entry[field] = None
            else:
                entry[field] = None
        stage = entry.get("stage", "unknown")
        by_stage.setdefault(stage, []).append(entry)
    return by_stage


def _get_research_notes(conn) -> list[dict]:
    """Get all research notes."""
    rows = conn.execute(
        "SELECT note_id, agent_id, status, observation, potential_edge, "
        "age_cycles, created_at FROM research_notes "
        "ORDER BY created_at DESC"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_failed_cycles(conn) -> list[dict]:
    """Get recent failed cycles."""
    rows = conn.execute(
        "SELECT agent_id, cycle, timestamp, error, model_used "
        "FROM failed_cycles ORDER BY timestamp DESC LIMIT 20"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_strategy_funnel(conn) -> dict[str, int]:
    """Get strategy count by stage."""
    rows = conn.execute(
        "SELECT stage, COUNT(*) as cnt FROM strategy_registry GROUP BY stage"
    ).fetchall()
    return {r["stage"]: r["cnt"] for r in rows}


def _get_risk_log(conn) -> list[dict]:
    """Get recent risk gate decisions."""
    rows = conn.execute(
        "SELECT id, created_at, agent_id, instruction_type, status, risk_check_result "
        "FROM instruction_queue ORDER BY id DESC LIMIT 50"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_messages(conn) -> list[dict]:
    """Get recent agent messages."""
    rows = conn.execute(
        "SELECT created_at, from_agent, to_agent, message_type, priority, "
        "substr(payload, 1, 200) as payload_preview, status "
        "FROM agent_messages ORDER BY id DESC LIMIT 30"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_feeds(conn) -> list[dict]:
    """Get latest supplementary feed values."""
    rows = conn.execute(
        "SELECT feed_name, timestamp, value, source "
        "FROM supplementary_feeds "
        "GROUP BY feed_name "
        "HAVING timestamp = MAX(timestamp) "
        "ORDER BY feed_name"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_recent_trades(conn) -> list[dict]:
    """Get recent trades."""
    rows = conn.execute(
        "SELECT timestamp, agent_id, strategy_id, pair, action, size_usd, "
        "price, fill_price, paper, status "
        "FROM trades ORDER BY id DESC LIMIT 30"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_system_state(conn) -> dict:
    """Get all system_state key-value pairs."""
    rows = conn.execute("SELECT key, value FROM system_state").fetchall()
    result = {}
    for r in rows:
        try:
            result[r["key"]] = json.loads(r["value"])
        except (json.JSONDecodeError, TypeError):
            result[r["key"]] = r["value"]
    return result


def _get_agent_summaries(conn, config: dict) -> list[dict]:
    """Build per-agent summary data."""
    agents_cfg = config.get("agents", {})
    enabled_agents = [
        aid for aid, acfg in agents_cfg.items()
        if isinstance(acfg, dict) and acfg.get("enabled", False)
    ]
    summaries = []
    for agent_id in enabled_agents:
        acfg = agents_cfg[agent_id]

        status_row = conn.execute(
            "SELECT value FROM system_state WHERE key = ?",
            (f"agent_status_{agent_id}",),
        ).fetchone()
        status = "active"
        if status_row:
            try:
                status = json.loads(status_row["value"]).get("status", "active")
            except (json.JSONDecodeError, TypeError):
                pass

        cycle_row = conn.execute(
            "SELECT MAX(cycle) as max_cycle FROM events WHERE agent_id = ?",
            (agent_id,),
        ).fetchone()
        cycles = cycle_row["max_cycle"] if cycle_row and cycle_row["max_cycle"] else 0

        last_success = conn.execute(
            "SELECT timestamp FROM events "
            "WHERE agent_id = ? AND event_type = 'cycle_complete' "
            "ORDER BY timestamp DESC LIMIT 1",
            (agent_id,),
        ).fetchone()
        if last_success:
            fail_row = conn.execute(
                "SELECT COUNT(*) as cnt FROM failed_cycles "
                "WHERE agent_id = ? AND timestamp > ?",
                (agent_id, last_success["timestamp"]),
            ).fetchone()
            consec_failures = fail_row["cnt"] if fail_row else 0
        else:
            fail_row = conn.execute(
                "SELECT COUNT(*) as cnt FROM failed_cycles WHERE agent_id = ?",
                (agent_id,),
            ).fetchone()
            consec_failures = fail_row["cnt"] if fail_row else 0

        cadence = acfg.get("cadence_hours", 4)
        wake_row = conn.execute(
            "SELECT payload FROM events "
            "WHERE agent_id = ? AND event_type = 'wake_schedule_update' "
            "ORDER BY timestamp DESC LIMIT 1",
            (agent_id,),
        ).fetchone()
        if wake_row:
            try:
                cadence = json.loads(wake_row["payload"]).get("base_cadence_hours", cadence)
            except (json.JSONDecodeError, TypeError):
                pass

        notes_row = conn.execute(
            "SELECT payload FROM events "
            "WHERE agent_id = ? AND event_type = 'cycle_notes' "
            "ORDER BY timestamp DESC LIMIT 1",
            (agent_id,),
        ).fetchone()
        last_notes = ""
        if notes_row:
            try:
                data = json.loads(notes_row["payload"])
                if isinstance(data, dict):
                    last_notes = data.get("notes", "")
                    if isinstance(last_notes, dict):
                        last_notes = last_notes.get("cycle_notes", str(last_notes))
                    elif not last_notes:
                        last_notes = data.get("cycle_notes", str(data))
                else:
                    last_notes = str(data)
            except (json.JSONDecodeError, TypeError):
                last_notes = str(notes_row["payload"])

        summaries.append({
            "agent_id": agent_id,
            "status": status,
            "cycles": cycles,
            "capital": acfg.get("capital_allocated", 0.0),
            "cadence": cadence,
            "consec_failures": consec_failures,
            "last_notes": last_notes,
        })
    return summaries


def _get_sirs(conn) -> list[dict]:
    """Get system improvement requests."""
    rows = conn.execute(
        "SELECT request_id, created_at, agent_id, cycle, title, problem, "
        "impact, category, priority, status, status_note "
        "FROM system_improvement_requests ORDER BY id DESC LIMIT 30"
    ).fetchall()
    return [dict(r) for r in rows]


def _get_owner_requests(conn) -> list[dict]:
    """Get owner requests from agents."""
    rows = conn.execute(
        "SELECT request_id, created_at, agent_id, cycle, type, urgency, "
        "title, description, blocked_work, status, resolution_note "
        "FROM owner_requests ORDER BY id DESC LIMIT 20"
    ).fetchall()
    return [dict(r) for r in rows]


# --------------------------------------------------------------------------
# HTML helpers
# --------------------------------------------------------------------------

def _fmt_metric(v, pct=False, color_thresh=None):
    """Format a numeric metric as an HTML table cell."""
    if v is None:
        return "<td style='color:#555'>-</td>"
    if pct:
        val_str = f"{v:.1f}%"
    elif isinstance(v, float):
        val_str = f"{v:.3f}"
    else:
        val_str = str(v)
    color = ""
    if color_thresh is not None and isinstance(v, (int, float)):
        color = " style='color:#4CAF50'" if v >= color_thresh else " style='color:#f44336'"
    return f"<td{color}>{val_str}</td>"


def _build_strategy_card(s: dict, stage_colors: dict) -> str:
    """Build an HTML card for a strategy showing cumulative results."""
    stage = s.get("stage", "unknown")
    scolor = stage_colors.get(stage, "#888")
    cfg = s.get("config") or {}
    bt = s.get("backtest_results") or {}
    rob = s.get("robustness_results") or {}
    paper = s.get("paper_results") or {}

    strategy_id = escape(str(s.get("strategy_id", "")))
    agent_id = escape(str(s.get("agent_id", "")))
    created = str(s.get("created_at", ""))[:10]
    updated = str(s.get("updated_at", ""))[:10]

    # Hypothesis info from config
    hypothesis_desc = escape(str(cfg.get("description", cfg.get("hypothesis", "")))[:200])
    kill_reason = escape(str(cfg.get("kill_reason", ""))[:120]) if stage == "graveyard" else ""
    killed_from = escape(str(cfg.get("killed_from_stage", ""))) if stage == "graveyard" else ""

    html = (
        f"<div style='background:#16213e;border-radius:8px;padding:14px;margin-bottom:10px;"
        f"border-left:3px solid {scolor};'>"
        f"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;'>"
        f"<b style='color:#e0e0e0;'>{strategy_id}</b>"
        f"<span style='font-size:0.8em;color:#888;'>{agent_id} &middot; {created} &rarr; {updated}</span>"
        f"</div>"
    )

    if hypothesis_desc:
        html += f"<div style='color:#aaa;font-size:0.85em;margin-bottom:8px;'>{hypothesis_desc}</div>"

    if stage == "graveyard" and kill_reason:
        html += (
            f"<div style='color:#f44336;font-size:0.85em;margin-bottom:8px;'>"
            f"Killed from <b>{killed_from}</b>: {kill_reason}</div>"
        )

    # Backtest results (shown for backtest+ stages)
    if bt:
        html += _build_results_row("Backtest", {
            "Return": (bt.get("total_return"), True, 0),
            "Sharpe": (bt.get("sharpe_ratio"), False, 0.5),
            "Max DD": (bt.get("max_drawdown"), True, None),
            "Win Rate": (bt.get("win_rate"), True, 50),
            "Trades": (bt.get("trade_count"), False, None),
            "Bench": (bt.get("benchmark_return"), True, None),
        })

    # Robustness results (shown for robustness+ stages)
    if rob and isinstance(rob, dict):
        html += _build_results_row("Robustness", {
            "Sharpe %ile": (rob.get("sharpe_percentile"), True, 90),
            "Return %ile": (rob.get("total_return_percentile"), True, 90),
            "Rand Sharpe %ile": (rob.get("random_entry_sharpe_percentile"), True, 90),
            "Rand Return %ile": (rob.get("random_entry_return_percentile"), True, 90),
        })

    # Paper results (shown for paper+ stages)
    if paper and isinstance(paper, dict):
        html += _build_results_row("Paper", {
            "PnL": (paper.get("pnl"), False, 0),
            "Return": (paper.get("total_return"), True, 0),
            "Sharpe": (paper.get("sharpe_ratio"), False, 0.5),
            "Trades": (paper.get("trade_count"), False, None),
            "Duration": (paper.get("duration_days"), False, None),
        })

    html += "</div>\n"
    return html


def _build_results_row(label: str, metrics: dict) -> str:
    """Build a compact metrics row for a strategy card."""
    items = ""
    for name, (val, is_pct, thresh) in metrics.items():
        if val is None:
            continue
        if is_pct and isinstance(val, (int, float)):
            val_str = f"{val:.1f}%"
        elif isinstance(val, float):
            val_str = f"{val:.3f}"
        else:
            val_str = str(val)
        color = "#e0e0e0"
        if thresh is not None and isinstance(val, (int, float)):
            color = "#4CAF50" if val >= thresh else "#f44336"
        items += f"<span style='margin-right:14px;'><span style='color:#888;'>{name}:</span> <b style='color:{color};'>{val_str}</b></span>"

    if not items:
        return ""
    return (
        f"<div style='font-size:0.82em;margin-bottom:4px;padding:4px 8px;background:#1a1a2e;border-radius:4px;'>"
        f"<span style='color:#81d4fa;font-weight:bold;margin-right:8px;'>{label}</span>{items}</div>"
    )


# --------------------------------------------------------------------------
# HTML builder
# --------------------------------------------------------------------------

def _build_html(
    equity_data: list[dict],
    strategies: list[dict],
    strategies_by_stage: dict[str, list[dict]],
    research_notes: list[dict],
    failed_cycles: list[dict],
    funnel: dict[str, int],
    risk_log: list[dict],
    messages: list[dict],
    feeds: list[dict],
    trades: list[dict],
    system_state: dict,
    agent_summaries: list[dict],
    sirs: list[dict],
    owner_requests: list[dict],
    config: dict,
    generated_at: str,
) -> str:
    """Assemble the full HTML dashboard."""

    stage_colors = {
        "hypothesis": "#888",
        "backtest": "#d4a017",
        "robustness": "#e07000",
        "paper": "#2196F3",
        "live": "#4CAF50",
        "graveyard": "#f44336",
    }

    # --- Executive summary ---
    exec_summary = system_state.get("executive_summary", {})
    if isinstance(exec_summary, dict) and exec_summary.get("summary"):
        summary_text = escape(exec_summary["summary"])
        summary_meta = escape(str(exec_summary.get("generated_at", ""))[:16])
        summary_cycle = exec_summary.get("cycle", "?")
        exec_summary_html = (
            f"<div style='background:#0f3460;border-radius:8px;padding:16px;margin-bottom:20px;"
            f"border-left:4px solid #4fc3f7;'>"
            f"<div style='color:#4fc3f7;font-size:0.75em;text-transform:uppercase;margin-bottom:6px;'>"
            f"Executive Summary &mdash; Cycle {summary_cycle}</div>"
            f"<div style='font-size:0.95em;line-height:1.5;'>{summary_text}</div>"
            f"<div style='color:#555;font-size:0.7em;margin-top:6px;'>{summary_meta}</div>"
            f"</div>"
        )
    else:
        exec_summary_html = (
            "<div style='background:#16213e;border-radius:8px;padding:16px;margin-bottom:20px;"
            "color:#555;font-style:italic;'>Awaiting first cycle completion for executive summary.</div>"
        )

    # --- Equity chart as inline SVG ---
    equity_svg = _build_equity_svg(equity_data)

    # --- Strategy funnel ---
    funnel_html = _build_funnel_html(funnel, stage_colors)

    # --- Research notes: split into active and archived ---
    active_notes = []
    archived_notes = []
    for n in research_notes:
        status = n.get("status", "")
        if status in ("promoted", "abandoned", "expired"):
            archived_notes.append(n)
        else:
            active_notes.append(n)

    note_status_colors = {
        "research": "#4fc3f7",
        "active": "#4CAF50",
        "promoted": "#d4a017",
        "abandoned": "#f44336",
        "expired": "#888",
    }

    def _render_note_rows(notes):
        rows = ""
        for n in notes:
            status = n.get("status", "")
            scolor = note_status_colors.get(status, "#888")
            obs = escape(str(n.get("observation", ""))[:120])
            edge = escape(str(n.get("potential_edge", ""))[:80])
            rows += (
                f"<tr>"
                f"<td>{escape(str(n.get('note_id', '')))}</td>"
                f"<td>{escape(str(n.get('agent_id', '')))}</td>"
                f"<td style='color:{scolor};font-weight:bold'>{escape(status)}</td>"
                f"<td>{n.get('age_cycles', 0)}c</td>"
                f"<td>{obs}</td>"
                f"<td>{edge}</td>"
                f"</tr>\n"
            )
        return rows

    active_note_rows = _render_note_rows(active_notes)
    archived_note_rows = _render_note_rows(archived_notes)
    note_table_header = "<tr><th>Note ID</th><th>Agent</th><th>Status</th><th>Age</th><th>Observation</th><th>Potential Edge</th></tr>"

    # --- Strategy tab content ---
    strat_tab_stages = ["hypothesis", "backtest", "robustness", "paper", "live", "graveyard"]
    strat_tab_contents = {}
    for stage in strat_tab_stages:
        strats = strategies_by_stage.get(stage, [])
        if strats:
            cards = "".join(_build_strategy_card(s, stage_colors) for s in strats)
            strat_tab_contents[stage] = cards
        else:
            color = stage_colors.get(stage, "#888")
            strat_tab_contents[stage] = f"<p style='color:#555;padding:20px;'>No strategies at <span style='color:{color};'>{stage}</span> stage</p>"

    # --- Failed cycles table ---
    fail_rows = ""
    for fc in failed_cycles:
        err = escape(str(fc.get("error", ""))[:100])
        fail_rows += (
            f"<tr>"
            f"<td>{escape(str(fc.get('timestamp', ''))[:16])}</td>"
            f"<td>{escape(str(fc.get('agent_id', '')))}</td>"
            f"<td>{fc.get('cycle', '')}</td>"
            f"<td>{escape(str(fc.get('model_used', '')))}</td>"
            f"<td style='color:#f44336'>{err}</td>"
            f"</tr>\n"
        )

    # --- Risk gate log table ---
    risk_rows = ""
    for r in risk_log:
        status = r.get("status", "")
        status_class = "approved" if status == "approved" else (
            "rejected" if status == "rejected" else ""
        )
        check_result = ""
        if r.get("risk_check_result"):
            try:
                check = json.loads(r["risk_check_result"])
                check_result = check.get("reason", "")
            except (json.JSONDecodeError, TypeError):
                check_result = str(r.get("risk_check_result", ""))
        risk_rows += (
            f"<tr>"
            f"<td>{r.get('id', '')}</td>"
            f"<td>{escape(str(r.get('created_at', ''))[:16])}</td>"
            f"<td>{escape(r.get('agent_id', ''))}</td>"
            f"<td>{escape(r.get('instruction_type', ''))}</td>"
            f"<td class='{status_class}'>{escape(status)}</td>"
            f"<td>{escape(check_result[:60])}</td>"
            f"</tr>\n"
        )

    # --- SIR table ---
    sir_status_colors = {
        "pending": "#d4a017",
        "shipped": "#4CAF50",
        "declined": "#f44336",
        "acknowledged": "#2196F3",
    }
    sir_rows = ""
    pending_sir_count = sum(1 for s in sirs if s.get("status") == "pending")
    for s in sirs:
        status = s.get("status", "pending")
        scolor = sir_status_colors.get(status, "#888")
        sir_rows += (
            f"<tr>"
            f"<td>{escape(str(s.get('request_id', '')))}</td>"
            f"<td>{escape(str(s.get('created_at', ''))[:10])}</td>"
            f"<td>{escape(s.get('agent_id', ''))}</td>"
            f"<td>{escape(s.get('category', ''))}</td>"
            f"<td>{escape(s.get('priority', ''))}</td>"
            f"<td style='color:{scolor};font-weight:bold'>{escape(status)}</td>"
            f"<td>{escape(str(s.get('title', ''))[:80])}</td>"
            f"<td>{escape(str(s.get('problem', ''))[:100])}</td>"
            f"</tr>\n"
        )

    # --- Owner requests table ---
    or_status_colors = {
        "pending": "#d4a017",
        "resolved": "#4CAF50",
        "declined": "#f44336",
    }
    or_rows = ""
    pending_or_count = sum(1 for o in owner_requests if o.get("status") == "pending")
    for o in owner_requests:
        status = o.get("status", "pending")
        ocolor = or_status_colors.get(status, "#888")
        urgency = o.get("urgency", "normal")
        urgency_color = "#f44336" if urgency == "critical" else ("#d4a017" if urgency == "high" else "#888")
        or_rows += (
            f"<tr>"
            f"<td>{escape(str(o.get('request_id', '')))}</td>"
            f"<td>{escape(str(o.get('created_at', ''))[:10])}</td>"
            f"<td>{escape(o.get('agent_id', ''))}</td>"
            f"<td>{escape(o.get('type', ''))}</td>"
            f"<td style='color:{urgency_color};font-weight:bold'>{escape(urgency)}</td>"
            f"<td style='color:{ocolor};font-weight:bold'>{escape(status)}</td>"
            f"<td>{escape(str(o.get('title', ''))[:80])}</td>"
            f"<td>{escape(str(o.get('description', ''))[:100])}</td>"
            f"</tr>\n"
        )

    # --- Agent messages table ---
    msg_rows = ""
    for m in messages:
        msg_rows += (
            f"<tr>"
            f"<td>{escape(str(m.get('created_at', ''))[:16])}</td>"
            f"<td>{escape(m.get('from_agent', ''))}</td>"
            f"<td>{escape(m.get('to_agent', ''))}</td>"
            f"<td>{escape(m.get('message_type', ''))}</td>"
            f"<td>{escape(m.get('priority', ''))}</td>"
            f"<td>{escape(m.get('status', ''))}</td>"
            f"</tr>\n"
        )

    # --- Supplementary feeds table ---
    feed_rows = ""
    for f_ in feeds:
        val = f_.get("value")
        val_str = f"{val:.4f}" if isinstance(val, (int, float)) and val is not None else str(val)
        feed_rows += (
            f"<tr>"
            f"<td>{escape(f_.get('feed_name', ''))}</td>"
            f"<td>{val_str}</td>"
            f"<td>{escape(str(f_.get('timestamp', ''))[:16])}</td>"
            f"<td>{escape(f_.get('source', ''))}</td>"
            f"</tr>\n"
        )

    # --- Recent trades table ---
    trade_rows = ""
    for t in trades:
        mode = "paper" if t.get("paper") else "live"
        trade_rows += (
            f"<tr>"
            f"<td>{escape(str(t.get('timestamp', ''))[:16])}</td>"
            f"<td>{escape(t.get('agent_id', ''))}</td>"
            f"<td>{escape(t.get('pair', ''))}</td>"
            f"<td>{escape(t.get('action', ''))}</td>"
            f"<td>${t.get('size_usd', 0):,.2f}</td>"
            f"<td>${t.get('price', 0):,.2f}</td>"
            f"<td>{mode}</td>"
            f"<td>{escape(t.get('status', ''))}</td>"
            f"</tr>\n"
        )

    # --- System state ---
    cb_status = system_state.get("circuit_breaker_status", {})
    cb_label = cb_status.get("status", "normal") if isinstance(cb_status, dict) else str(cb_status)
    hwm = system_state.get("high_water_mark", {})
    hwm_val = hwm.get("amount", 0.0) if isinstance(hwm, dict) else 0.0

    backtest_count = funnel.get("backtest", 0) + funnel.get("robustness", 0)
    active_notes_count = len(active_notes)

    # --- Agent summary cards ---
    agent_summary_html = ""
    for a in agent_summaries:
        status_color = "#4CAF50" if a["status"] == "active" else "#f44336"
        fail_color = "#f44336" if a["consec_failures"] >= 3 else ("#d4a017" if a["consec_failures"] >= 1 else "#4CAF50")
        notes_preview = escape(str(a["last_notes"])[:500]) if a["last_notes"] else "<em>No cycle notes</em>"
        agent_summary_html += (
            f"<div style='background:#16213e;border-radius:8px;padding:16px;margin-bottom:12px;'>"
            f"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;'>"
            f"<h3 style='color:#81d4fa;margin:0;'>{escape(a['agent_id'])}</h3>"
            f"<span style='color:{status_color};font-weight:bold;text-transform:uppercase;'>{escape(a['status'])}</span>"
            f"</div>"
            f"<div style='display:flex;gap:20px;flex-wrap:wrap;margin-bottom:12px;font-size:0.9em;'>"
            f"<div><span style='color:#888;'>Cycles:</span> <b>{a['cycles']}</b></div>"
            f"<div><span style='color:#888;'>Capital:</span> <b>${a['capital']:,.2f}</b></div>"
            f"<div><span style='color:#888;'>Cadence:</span> <b>{a['cadence']}h</b></div>"
            f"<div><span style='color:#888;'>Consec. Failures:</span> <b style='color:{fail_color}'>{a['consec_failures']}</b></div>"
            f"</div>"
            f"<details><summary style='color:#888;cursor:pointer;font-size:0.85em;'>Last Cycle Notes</summary>"
            f"<div style='margin-top:8px;padding:10px;background:#1a1a2e;border-radius:4px;"
            f"font-size:0.85em;line-height:1.5;white-space:pre-wrap;max-height:300px;overflow-y:auto;'>"
            f"{notes_preview}</div></details>"
            f"</div>\n"
        )

    # --- Build strategy tabs HTML ---
    strat_tabs_html = ""
    for i, stage in enumerate(strat_tab_stages):
        count = funnel.get(stage, 0)
        color = stage_colors.get(stage, "#888")
        checked = " checked" if i == 0 else ""
        strat_tabs_html += f'<input type="radio" name="strat-tabs" id="strat-tab-{i}"{checked}>'
        strat_tabs_html += (
            f'<label for="strat-tab-{i}" class="tab-label">'
            f'<span style="color:{color};">{stage.title()}</span>'
            f' <span style="color:#555;font-size:0.8em;">({count})</span></label>\n'
        )
    for i, stage in enumerate(strat_tab_stages):
        strat_tabs_html += f'<div class="tab-content">{strat_tab_contents[stage]}</div>\n'

    # --- Build research notes tabs HTML ---
    research_tabs_html = (
        '<input type="radio" name="research-tabs" id="research-tab-0" checked>'
        f'<label for="research-tab-0" class="tab-label">Active ({len(active_notes)})</label>\n'
        '<input type="radio" name="research-tabs" id="research-tab-1">'
        f'<label for="research-tab-1" class="tab-label">Archived ({len(archived_notes)})</label>\n'
        f'<div class="tab-content"><table>{note_table_header}'
        f'{active_note_rows if active_note_rows else "<tr><td colspan=6>No active research notes</td></tr>"}'
        f'</table></div>\n'
        f'<div class="tab-content"><table>{note_table_header}'
        f'{archived_note_rows if archived_note_rows else "<tr><td colspan=6>No archived notes</td></tr>"}'
        f'</table></div>\n'
    )

    # --- Build operations tabs HTML ---
    ops_tabs = [
        ("Failed Cycles", len(failed_cycles),
         f"<table><tr><th>Time</th><th>Agent</th><th>Cycle</th><th>Model</th><th>Error</th></tr>"
         f"{fail_rows if fail_rows else '<tr><td colspan=5>No failed cycles</td></tr>'}</table>"),
        ("Risk Gate", len(risk_log),
         f"<table><tr><th>ID</th><th>Time</th><th>Agent</th><th>Type</th><th>Status</th><th>Reason</th></tr>"
         f"{risk_rows if risk_rows else '<tr><td colspan=6>No instructions processed</td></tr>'}</table>"),
        ("SIRs", len(sirs),
         f"<table><tr><th>ID</th><th>Date</th><th>Agent</th><th>Category</th><th>Priority</th><th>Status</th><th>Title</th><th>Problem</th></tr>"
         f"{sir_rows if sir_rows else '<tr><td colspan=8>No improvement requests</td></tr>'}</table>"),
        ("Owner Requests", len(owner_requests),
         f"<table><tr><th>ID</th><th>Date</th><th>Agent</th><th>Type</th><th>Urgency</th><th>Status</th><th>Title</th><th>Description</th></tr>"
         f"{or_rows if or_rows else '<tr><td colspan=8>No owner requests</td></tr>'}</table>"),
        ("Messages", len(messages),
         f"<table><tr><th>Time</th><th>From</th><th>To</th><th>Type</th><th>Priority</th><th>Status</th></tr>"
         f"{msg_rows if msg_rows else '<tr><td colspan=6>No messages</td></tr>'}</table>"),
    ]
    ops_tabs_html = ""
    for i, (label, count, content) in enumerate(ops_tabs):
        checked = " checked" if i == 0 else ""
        ops_tabs_html += f'<input type="radio" name="ops-tabs" id="ops-tab-{i}"{checked}>'
        ops_tabs_html += f'<label for="ops-tab-{i}" class="tab-label">{label} ({count})</label>\n'
    for _, _, content in ops_tabs:
        ops_tabs_html += f'<div class="tab-content">{content}</div>\n'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="refresh" content="60">
<title>Agentic Quant System Dashboard</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
           background: #1a1a2e; color: #e0e0e0; padding: 20px; max-width: 1400px; margin: 0 auto; }}
    h1 {{ color: #4fc3f7; margin-bottom: 5px; }}
    h2 {{ color: #81d4fa; margin: 25px 0 10px 0; border-bottom: 1px solid #333; padding-bottom: 5px; }}
    .meta {{ color: #888; font-size: 0.85em; margin-bottom: 20px; }}
    .status-bar {{ display: flex; gap: 15px; flex-wrap: wrap; margin-bottom: 20px; }}
    .status-card {{ background: #16213e; padding: 12px 18px; border-radius: 8px;
                   min-width: 130px; flex: 1; }}
    .status-card .label {{ color: #888; font-size: 0.75em; text-transform: uppercase; }}
    .status-card .value {{ font-size: 1.3em; font-weight: bold; margin-top: 3px; }}
    .status-card .value.ok {{ color: #4CAF50; }}
    .status-card .value.warn {{ color: #f44336; }}
    table {{ width: 100%; border-collapse: collapse; margin-bottom: 10px;
            background: #16213e; border-radius: 8px; overflow: hidden; }}
    th {{ background: #0f3460; padding: 10px 12px; text-align: left; font-size: 0.85em;
         text-transform: uppercase; color: #81d4fa; }}
    td {{ padding: 8px 12px; border-top: 1px solid #222; font-size: 0.9em; }}
    tr:hover {{ background: #1a1a40; }}
    .approved {{ color: #4CAF50; font-weight: bold; }}
    .rejected {{ color: #f44336; font-weight: bold; }}
    .svg-chart {{ background: #16213e; border-radius: 8px; padding: 15px; margin-bottom: 20px; }}
    .section {{ margin-bottom: 30px; }}
    .funnel {{ display: flex; gap: 8px; align-items: flex-end; padding: 20px 0; }}
    .funnel-stage {{ text-align: center; flex: 1; }}
    .funnel-bar {{ border-radius: 4px 4px 0 0; min-height: 8px; margin: 0 auto;
                  width: 80%; transition: height 0.3s; }}
    .funnel-count {{ font-size: 1.4em; font-weight: bold; margin-top: 6px; }}
    .funnel-label {{ font-size: 0.75em; color: #888; text-transform: uppercase; margin-top: 2px; }}
    .funnel-arrow {{ color: #555; font-size: 1.2em; align-self: center; padding-bottom: 30px; }}

    /* CSS-only tabs */
    .tab-group {{ margin-bottom: 10px; }}
    .tab-group input[type="radio"] {{ display: none; }}
    .tab-label {{ display: inline-block; padding: 8px 16px; cursor: pointer; color: #888;
                  border-bottom: 2px solid transparent; font-size: 0.85em; text-transform: uppercase;
                  transition: color 0.2s, border-color 0.2s; }}
    .tab-label:hover {{ color: #aaa; }}
    .tab-content {{ display: none; padding-top: 12px; }}

    /* Strategy tabs - 6 tabs */
    .tab-group input[name="strat-tabs"]:nth-of-type(1):checked ~ .tab-content:nth-of-type(1),
    .tab-group input[name="strat-tabs"]:nth-of-type(2):checked ~ .tab-content:nth-of-type(2),
    .tab-group input[name="strat-tabs"]:nth-of-type(3):checked ~ .tab-content:nth-of-type(3),
    .tab-group input[name="strat-tabs"]:nth-of-type(4):checked ~ .tab-content:nth-of-type(4),
    .tab-group input[name="strat-tabs"]:nth-of-type(5):checked ~ .tab-content:nth-of-type(5),
    .tab-group input[name="strat-tabs"]:nth-of-type(6):checked ~ .tab-content:nth-of-type(6) {{ display: block; }}

    /* Research tabs - 2 tabs */
    .tab-group input[name="research-tabs"]:nth-of-type(1):checked ~ .tab-content:nth-of-type(1),
    .tab-group input[name="research-tabs"]:nth-of-type(2):checked ~ .tab-content:nth-of-type(2) {{ display: block; }}

    /* Operations tabs - 5 tabs */
    .tab-group input[name="ops-tabs"]:nth-of-type(1):checked ~ .tab-content:nth-of-type(1),
    .tab-group input[name="ops-tabs"]:nth-of-type(2):checked ~ .tab-content:nth-of-type(2),
    .tab-group input[name="ops-tabs"]:nth-of-type(3):checked ~ .tab-content:nth-of-type(3),
    .tab-group input[name="ops-tabs"]:nth-of-type(4):checked ~ .tab-content:nth-of-type(4),
    .tab-group input[name="ops-tabs"]:nth-of-type(5):checked ~ .tab-content:nth-of-type(5) {{ display: block; }}

    /* Highlight active tab */
    .tab-group input:checked + .tab-label {{ color: #81d4fa; border-bottom-color: #81d4fa; }}
</style>
</head>
<body>
<h1>Agentic Quant System</h1>
<div class="meta">Generated: {generated_at} &mdash; auto-refreshes every 60s</div>

{exec_summary_html}

<div class="status-bar">
    <div class="status-card">
        <div class="label">Circuit Breaker</div>
        <div class="value {'ok' if cb_label == 'normal' else 'warn'}">{cb_label.upper()}</div>
    </div>
    <div class="status-card">
        <div class="label">High-Water Mark</div>
        <div class="value">${hwm_val:,.2f}</div>
    </div>
    <div class="status-card">
        <div class="label">Strategies</div>
        <div class="value">{len(strategies)}</div>
    </div>
    <div class="status-card">
        <div class="label">Research Notes</div>
        <div class="value">{active_notes_count}</div>
    </div>
    <div class="status-card">
        <div class="label">In Backtest</div>
        <div class="value">{backtest_count}</div>
    </div>
    <div class="status-card">
        <div class="label">Failed Cycles</div>
        <div class="value{' warn' if len(failed_cycles) > 5 else ''}">{len(failed_cycles)}</div>
    </div>
    <div class="status-card">
        <div class="label">Pending SIRs</div>
        <div class="value{' warn' if pending_sir_count > 0 else ''}">{pending_sir_count}</div>
    </div>
    <div class="status-card">
        <div class="label">Owner Requests</div>
        <div class="value{' warn' if pending_or_count > 0 else ''}">{pending_or_count}</div>
    </div>
    <div class="status-card">
        <div class="label">Recent Trades</div>
        <div class="value">{len(trades)}</div>
    </div>
</div>

<div class="section">
<h2>Agent State Summary</h2>
{agent_summary_html if agent_summary_html else "<p style='color:#888'>No enabled agents</p>"}
</div>

<div class="section">
<h2>Strategy Lifecycle Funnel</h2>
{funnel_html}
</div>

<div class="section">
<h2>Equity Curve</h2>
<div class="svg-chart">
{equity_svg}
</div>
</div>

<div class="section">
<h2>Strategy Lifecycle</h2>
<div class="tab-group">
{strat_tabs_html}
</div>
</div>

<div class="section">
<h2>Research Notes ({len(research_notes)} total)</h2>
<div class="tab-group">
{research_tabs_html}
</div>
</div>

<div class="section">
<h2>Recent Trades</h2>
<table>
<tr><th>Time</th><th>Agent</th><th>Pair</th><th>Action</th><th>Size</th><th>Price</th><th>Mode</th><th>Status</th></tr>
{trade_rows if trade_rows else "<tr><td colspan='8'>No trades recorded</td></tr>"}
</table>
</div>

<div class="section">
<h2>Operations</h2>
<div class="tab-group">
{ops_tabs_html}
</div>
</div>

<div class="section">
<h2>Supplementary Feeds</h2>
<table>
<tr><th>Feed</th><th>Value</th><th>Timestamp</th><th>Source</th></tr>
{feed_rows if feed_rows else "<tr><td colspan='4'>No feeds configured</td></tr>"}
</table>
</div>

</body>
</html>"""


def _build_equity_svg(equity_data: list[dict]) -> str:
    """Build a simple SVG line chart for equity data."""
    if not equity_data or len(equity_data) < 2:
        return "<p style='color:#888;text-align:center;padding:30px;'>Insufficient data for equity chart</p>"

    width = 800
    height = 250
    margin = 40

    values = [d["equity"] for d in equity_data]
    min_val = min(values) * 0.99
    max_val = max(values) * 1.01
    val_range = max_val - min_val
    if val_range == 0:
        val_range = 1

    n = len(values)
    x_step = (width - 2 * margin) / max(n - 1, 1)

    points = []
    for i, v in enumerate(values):
        x = margin + i * x_step
        y = margin + (1 - (v - min_val) / val_range) * (height - 2 * margin)
        points.append(f"{x:.1f},{y:.1f}")

    polyline = " ".join(points)

    y_labels = ""
    for frac in [0, 0.25, 0.5, 0.75, 1.0]:
        val = min_val + frac * val_range
        y = margin + (1 - frac) * (height - 2 * margin)
        y_labels += (
            f'<text x="{margin - 5}" y="{y + 4}" text-anchor="end" '
            f'font-size="10" fill="#888">${val:,.0f}</text>\n'
            f'<line x1="{margin}" y1="{y}" x2="{width - margin}" y2="{y}" '
            f'stroke="#333" stroke-width="0.5"/>\n'
        )

    return f"""<svg viewBox="0 0 {width} {height}" width="100%" xmlns="http://www.w3.org/2000/svg">
{y_labels}
<polyline points="{polyline}" fill="none" stroke="#4fc3f7" stroke-width="2"/>
<line x1="{margin}" y1="{margin}" x2="{margin}" y2="{height - margin}" stroke="#555" stroke-width="1"/>
<line x1="{margin}" y1="{height - margin}" x2="{width - margin}" y2="{height - margin}" stroke="#555" stroke-width="1"/>
</svg>"""


def _build_funnel_html(funnel: dict[str, int], stage_colors: dict[str, str]) -> str:
    """Build a visual funnel showing strategy counts per lifecycle stage."""
    stages = ["hypothesis", "backtest", "robustness", "paper", "live"]
    max_count = max((funnel.get(s, 0) for s in stages), default=1) or 1

    html = '<div class="funnel">\n'
    for i, stage in enumerate(stages):
        count = funnel.get(stage, 0)
        bar_height = max(8, int(count / max_count * 120))
        color = stage_colors.get(stage, "#888")

        if i > 0:
            html += '  <div class="funnel-arrow">&rarr;</div>\n'

        html += (
            f'  <div class="funnel-stage">\n'
            f'    <div class="funnel-bar" style="height:{bar_height}px;background:{color}"></div>\n'
            f'    <div class="funnel-count" style="color:{color}">{count}</div>\n'
            f'    <div class="funnel-label">{stage}</div>\n'
            f'  </div>\n'
        )

    gy_count = funnel.get("graveyard", 0)
    gy_height = max(8, int(gy_count / max_count * 120)) if max_count > 0 else 8
    html += (
        '  <div style="margin-left:20px;border-left:2px solid #333;padding-left:20px;">\n'
        '  <div class="funnel-stage">\n'
        f'    <div class="funnel-bar" style="height:{gy_height}px;background:#f44336"></div>\n'
        f'    <div class="funnel-count" style="color:#f44336">{gy_count}</div>\n'
        f'    <div class="funnel-label">graveyard</div>\n'
        '  </div>\n'
        '  </div>\n'
    )

    html += '</div>\n'
    return html
