"""Hypothesis: quant_primary_hyp_003_fear_greed_contrarian

Generated by agent quant_primary at cycle 1.
Config: {
  "hypothesis_id": "hyp_003_fear_greed_contrarian",
  "created_at": "2026-03-11T21:10:56.862137+00:00",
  "thesis": "Fear & Greed Index at extreme levels (\u226420 Extreme Fear or \u226580 Extreme Greed) predicts short-term BTC price reversal. Currently at 15 (Extreme Fear) for multiple consecutive days while BTC is already recovering (+1.3% today). The sentiment signal lags price, which means entering on sustained Fear while price is recovering captures the early phase of the recovery rally before sentiment normalizes. This is a daily-cadence contrarian strategy using a single clean sentiment indicator.",
  "strategy_type": "sentiment",
  "target_pairs": [
    "BTC/USD"
  ],
  "target_regimes": [
    "post_event",
    "high_vol"
  ],
  "signal_description": "Daily signal. Entry long: Fear & Greed \u2264 20 AND BTC 24h return > 0% (price is recovering despite fear). Entry size: 25% of capital. Hold until Fear & Greed crosses above 40 (neutral territory) OR 14 calendar days max hold. Entry short: Fear & Greed \u2265 80 AND BTC 24h return < 0% (price falling despite greed). Exit short: Fear & Greed crosses below 60 or 14 days. Position is mutually exclusive with hyp_001 and hyp_002 for capital \u2014 if those are active, reduce size to 15%.",
  "expected_trade_frequency": "1-3 trades per month (extreme readings are infrequent by definition)",
  "expected_behavior": "Low trade frequency means backtest results will be underpowered. Primary validation must come from paper trading and regime analysis. Expected to perform well post-crash and post-euphoria, poorly in sideways grinding markets where Fear oscillates between 30-60.",
  "success_criteria": {
    "metric": "pnl_vs_benchmark",
    "threshold": 1.05,
    "minimum_trade_count": 8,
    "evaluation_window": "90d backtest, then 21d paper (longer paper to capture more trades)",
    "robustness": {
      "random_entry_percentile_min": 60,
      "return_permutation_percentile_min": 60
    },
    "rationale": "Low trade count (8 minimum in 90d) means backtest is only indicative. Lower robustness thresholds reflect that with 8-15 trades, statistical power is limited. Paper trading over 21 days weighted more heavily than backtest. Using PnL vs benchmark (BTC hodl) rather than Sharpe because this is an infrequent event strategy \u2014 Sharpe is poorly estimated with few trades. Must beat BTC hodl by 5% risk-adjusted to justify complexity."
  },
  "counterfactual_benchmark": {
    "description": "Naive contrarian: buy BTC every time Fear & Greed drops below 20, regardless of price action confirmation",
    "implementation": "Daily: if Fear & Greed \u2264 20, allocate 25% to BTC. If \u2265 80, go to cash from BTC. No price confirmation filter.",
    "null_hypothesis": "If adding the price-confirmation filter (BTC 24h return > 0%) does not improve results vs naive Fear & Greed threshold buying, the filter adds no value and the thesis reduces to 'buy on fear.'"
  },
  "failure_modes": [
    "Fear & Greed stays at 15 while BTC continues declining \u2014 knife-catching in genuine bear market",
    "90d backtest contains too few extreme fear events for meaningful statistics",
    "Sentiment data has 1-day lag \u2014 may miss the best entry window",
    "Fear & Greed is a composite of many indicators including price itself \u2014 partially endogenous signal"
  ],
  "code_module": "strategies/backtest/primary_hyp_003_fear_greed_contrarian.py"
}
"""

import math

from strategies.base import BaseStrategy, Signal


class FearGreedContrarian(BaseStrategy):
    """Fear & Greed contrarian approximated using BTC 5-day return extremes.

    Since Fear & Greed data is not in the OHLCV cache, we approximate the
    sentiment signal using deeply negative 5-day returns (proxy for extreme fear)
    combined with a positive current-candle confirmation (price recovering).
    Entry: 5d return < -15% AND current 4h return > 0. Exit: 5d return > -5%.
    """

    LOOKBACK_5D = 30   # 30 x 4h bars ≈ 5 days
    FEAR_THRESHOLD = -0.15   # -15% 5d return = proxy for extreme fear
    EXIT_THRESHOLD = -0.05   # -5% 5d return = recovery
    MAX_HOLD = 84            # 14 days at 4h
    SIZE_PCT = 0.25

    def __init__(self, **kwargs):
        self._direction = None
        self._hold_count = 0

    def name(self) -> str:
        return "quant_primary_hyp_003_fear_greed_contrarian"

    def required_feeds(self) -> list[str]:
        return ["BTC/USD:4h"]

    def on_data(self, data: dict) -> list[Signal]:
        candles = data.get("candles_so_far", [])
        pair = data.get("pair", "BTC/USD")
        if len(candles) < self.LOOKBACK_5D + 2:
            return []

        closes = [c["close"] for c in candles]
        ret_5d = (closes[-1] - closes[-1 - self.LOOKBACK_5D]) / closes[-1 - self.LOOKBACK_5D]
        current_up = closes[-1] > closes[-2]
        signals = []

        if self._direction is None:
            if ret_5d < self.FEAR_THRESHOLD and current_up:
                signals.append(Signal(action="buy", pair=pair, size_pct=self.SIZE_PCT,
                                      order_type="market",
                                      rationale=f"5d_ret={ret_5d:.3f} recovering"))
                self._direction = "long"
                self._hold_count = 0
        else:
            self._hold_count += 1
            recovered = ret_5d > self.EXIT_THRESHOLD
            if recovered or self._hold_count >= self.MAX_HOLD:
                signals.append(Signal(action="close", pair=pair, size_pct=1.0,
                                      order_type="market",
                                      rationale=f"exit 5d_ret={ret_5d:.3f}"))
                self._direction = None
                self._hold_count = 0

        return signals
