"""Hypothesis: quant_primary_hyp_002_btc_fear_reversal

Generated by agent quant_primary at cycle 5.
Config: {
  "hypothesis_id": "hyp_002_btc_fear_reversal",
  "created_at": "2026-03-12T18:05:59.948667+00:00",
  "thesis": "When Fear & Greed Index drops to Extreme Fear (<=20) AND BTC's rolling 14-day Sharpe (4h) falls below -10 (annualized), subsequent 3-7 day returns are strongly positive. A momentum confirmation (4h close above prior 4h high) filters for the actual inflection point. The combined signal captures genuine capitulation episodes, not just low sentiment.",
  "strategy_type": "sentiment / contrarian momentum",
  "target_pairs": [
    "BTC/USD"
  ],
  "target_regimes": [
    "trending_bear",
    "high_vol",
    "post_event"
  ],
  "signal_description": "Entry: Fear & Greed <=20 AND rolling 14d Sharpe <-10 AND current 4h close > prior 4h high. Size: 80% capital. Exit: Sharpe crosses above 0 OR Fear & Greed >=35 OR -8% stop loss OR 40-period max hold.",
  "expected_trade_frequency": "1-3 trades per month",
  "expected_behavior": "Infrequent, high-conviction entries at capitulation. Will miss rallies without extreme fear. 90d backtest may have only 2-4 qualifying episodes \u2014 sample size is a known limitation.",
  "success_criteria": {
    "metric": "pnl_vs_benchmark",
    "threshold": 0.05,
    "minimum_trade_count": 8,
    "evaluation_window": "90d backtest + 14d paper",
    "robustness": {
      "random_entry_percentile_min": 85,
      "return_permutation_percentile_min": 75
    },
    "rationale": "Outperform hodl_btc by 5%+ over 90d. High random-entry bar (85th pct) \u2014 timing signal is the thesis, must beat random entries convincingly."
  },
  "counterfactual_benchmark": {
    "description": "Naive FG-only BTC buy \u2014 buy when FG<=20, sell when FG>=35, no other filters",
    "implementation": "Daily: buy BTC at open when FG<=20 and not in position. Sell when FG>=35.",
    "null_hypothesis": "If hyp_002 does not outperform naive FG-only strategy on risk-adjusted basis, the Sharpe filter and momentum confirmation add no value."
  },
  "failure_modes": [
    "Extended bear market \u2014 fear stays extreme for months (2022-style)",
    "FG daily resolution lags 4h price signal \u2014 bottom may be past before signal fires",
    "90d backtest likely has only 2-4 episodes \u2014 insufficient for statistical confidence",
    "8% stop may be hit before reversal in high-vol environment"
  ]
}
"""

# TODO: Implement strategy module conforming to BaseStrategy interface.
