"""Hypothesis: quant_primary_hyp_001_ethbtc_stat_arb

Generated by agent quant_primary at cycle 5.
Config: {
  "hypothesis_id": "hyp_001_ethbtc_stat_arb",
  "created_at": "2026-03-12T18:05:59.948667+00:00",
  "thesis": "ETH and BTC are cointegrated with a statistically confirmed spread. When the spread (ETH_price - hedge_ratio * BTC_price) deviates more than 1.5 standard deviations from its rolling mean, it mean-reverts with a half-life of approximately 44 hours. Trading this spread \u2014 long ETH / short BTC when ETH is relatively cheap, short ETH / long BTC when ETH is relatively expensive \u2014 should produce positive risk-adjusted returns independent of broad crypto direction.",
  "strategy_type": "mean-reversion / stat-arb",
  "target_pairs": [
    "ETH/USD",
    "BTC/USD"
  ],
  "target_regimes": [
    "ranging",
    "trending_bull",
    "trending_bear"
  ],
  "signal_description": "Rolling 30-period (5-day at 4h) OLS regression of ETH on BTC to estimate dynamic hedge ratio. Compute spread = ETH - hedge*BTC - intercept. Z-score = (spread - rolling_mean) / rolling_std. Entry at |z| > 1.5: z < -1.5 \u2192 long ETH + short BTC; z > 1.5 \u2192 short ETH + long BTC. Exit at |z| < 0.3 (equilibrium). Stop at |z| > 3.0 (regime break). 40% capital per leg.",
  "expected_trade_frequency": "3-5 trades per week",
  "expected_behavior": "Positive returns in all regimes where cointegration holds. May underperform during ETH-specific shocks. High spread persistence (lag-1 = 0.94) means trades may take 1-3 days to resolve.",
  "success_criteria": {
    "metric": "sharpe_ratio",
    "threshold": 1.2,
    "minimum_trade_count": 25,
    "evaluation_window": "90d backtest + 7d paper",
    "robustness": {
      "random_entry_percentile_min": 75,
      "return_permutation_percentile_min": 70
    },
    "rationale": "Sharpe > 1.2 with 25+ trades. Lower random-entry bar (75th pct) because cointegrated spread has structural mean-reversion \u2014 even random entries have some edge. Z-score signal should add incrementally above that."
  },
  "counterfactual_benchmark": {
    "description": "Simple ETH/BTC ratio MA strategy \u2014 hold ETH when ratio < 30-period MA, hold BTC otherwise",
    "implementation": "Each 4h: if ETH/BTC < 30-period MA of ratio, hold 50% ETH / 50% BTC. Else hold 100% BTC.",
    "null_hypothesis": "If hyp_001 Sharpe does not exceed this ratio-MA strategy, z-score signal and stop logic add no value."
  },
  "failure_modes": [
    "Cointegration breaks due to ETH-specific structural event",
    "Hedge ratio unstable over time \u2014 rolling OLS mitigates but cannot eliminate",
    "High spread persistence (lag-1=0.94) causes prolonged drawdowns before reversion",
    "Small capital makes balancing notional legs difficult vs Kraken minimums"
  ]
}
"""

# TODO: Implement strategy module conforming to BaseStrategy interface.
