"""Hypothesis: quant_primary_hyp_002_btc_4h_oscillation

Generated by agent quant_primary at cycle 1.
Config: {
  "hypothesis_id": "hyp_002_btc_4h_oscillation",
  "created_at": "2026-03-11T21:10:56.862137+00:00",
  "thesis": "BTC/USD 4h returns show consistent negative autocorrelation at lag 16 (-0.271), confirmed across multiple analysis cycles. This implies a ~64-hour (2.67-day) oscillation cycle where a sequence of strong 4h candles is followed by mean reversion approximately 64 hours later. The edge is in fading extreme 4h moves after the oscillation window has elapsed. Current regime context (post-crash recovery, Extreme Fear) adds a contrarian bias \u2014 sentiment extremes at Fear & Greed 15 historically precede recoveries.",
  "strategy_type": "mean-reversion",
  "target_pairs": [
    "BTC/USD"
  ],
  "target_regimes": [
    "ranging",
    "post_event",
    "high_vol"
  ],
  "signal_description": "Compute 16-period (64h) cumulative return for BTC/USD on 4h bars. When 16-period cum return > +4% (top quartile of distribution, ~1 std), go short bias \u2014 reduce position or fade. When 16-period cum return < -4%, go long bias \u2014 enter or increase position. Specifically: if 16-period cum return < -4% AND current 4h return is positive (confirming turn), buy BTC with 20% of capital. Exit when 16-period cum return crosses zero or 32 bars (128h) max hold. Secondary filter: Fear & Greed < 25 adds +50% to size (max 30% of capital) as contrarian amplifier.",
  "expected_trade_frequency": "3-6 trades per month (signal fires approximately every 2-3 weeks)",
  "expected_behavior": "Should perform best in ranging or recovering regimes. Will underperform badly in sustained trends \u2014 if BTC trends up for 30+ days, the 16-period negative autocorrelation signal produces losing short-bias trades. Strategy should be regime-filtered: disable if 30-day trend strength (BTC 30d return) exceeds +20%.",
  "success_criteria": {
    "metric": "sharpe_ratio",
    "threshold": 0.8,
    "minimum_trade_count": 15,
    "evaluation_window": "90d backtest, then 10d paper",
    "robustness": {
      "random_entry_percentile_min": 75,
      "return_permutation_percentile_min": 65
    },
    "rationale": "Entry signal is the thesis here (lag-16 oscillation), so random entry percentile should be higher (75) \u2014 if random entries match performance, the timing signal is worthless. Lower Sharpe threshold (0.8) reflects that 90-day backtest at 4h timeframe yields only ~15-25 trades \u2014 insufficient for high-confidence Sharpe estimates. Minimum 15 trades required. Lower permutation threshold (65) because trades are independent short-term bets, so path dependency matters less."
  },
  "counterfactual_benchmark": {
    "description": "Simple BTC 64h RSI fade \u2014 buy when RSI(16) < 30, sell when RSI(16) > 70",
    "implementation": "Standard RSI with period=16 on 4h bars. Long when RSI < 30, close when RSI > 50. Short when RSI > 70, close when RSI < 50.",
    "null_hypothesis": "If the autocorrelation-based cumulative return signal does not outperform a simple RSI(16) on BTC at the same timeframe, the autocorrelation framing adds no value over standard momentum indicators."
  },
  "failure_modes": [
    "BTC enters sustained uptrend invalidating mean-reversion assumption",
    "Negative autocorrelation at lag 16 is spurious (Ljung-Box p-values not yet available to confirm \u2014 sir_011 bug)",
    "Trade frequency too low in 90d backtest to distinguish skill from luck",
    "Fear & Greed amplifier fires at the wrong time during genuine panic events",
    "Post-event recovery means current conditions may not generalize to future data"
  ],
  "code_module": "strategies/backtest/primary_hyp_002_btc_4h_oscillation.py"
}
"""

import math

from strategies.base import BaseStrategy, Signal


class BTC4hOscillationV2(BaseStrategy):
    """BTC 4h oscillation v2: fade 16-period cum-return extremes with looser thresholds."""

    LOOKBACK = 16
    ROLLING = 30
    ENTRY_THRESHOLD = 0.04   # 4% cumulative return threshold (not z-score based)
    MAX_HOLD = 32            # 32 candles = 128h
    SIZE_PCT = 0.20
    STOP_PCT = 0.05

    def __init__(self, **kwargs):
        self._direction = None
        self._hold_count = 0
        self._entry_price = None
        self._entry_cum_ret = None

    def name(self) -> str:
        return "quant_primary_hyp_002_btc_4h_oscillation"

    def required_feeds(self) -> list[str]:
        return ["BTC/USD:4h"]

    def on_data(self, data: dict) -> list[Signal]:
        candles = data.get("candles_so_far", [])
        pair = data.get("pair", "BTC/USD")
        if len(candles) < self.LOOKBACK + 2:
            return []

        closes = [c["close"] for c in candles]
        cum_ret = (closes[-1] - closes[-1 - self.LOOKBACK]) / closes[-1 - self.LOOKBACK]
        current_price = closes[-1]
        prev_price = closes[-2]
        signals = []

        if self._direction is None:
            # Entry: extreme 64h move AND current candle confirms turn
            if cum_ret < -self.ENTRY_THRESHOLD and current_price > prev_price:
                signals.append(Signal(action="buy", pair=pair, size_pct=self.SIZE_PCT,
                                      order_type="market",
                                      rationale=f"64h ret={cum_ret:.3f}, turning up"))
                self._direction = "long"
                self._hold_count = 0
                self._entry_price = current_price
                self._entry_cum_ret = cum_ret
            elif cum_ret > self.ENTRY_THRESHOLD and current_price < prev_price:
                signals.append(Signal(action="sell", pair=pair, size_pct=self.SIZE_PCT,
                                      order_type="market",
                                      rationale=f"64h ret={cum_ret:.3f}, turning down"))
                self._direction = "short"
                self._hold_count = 0
                self._entry_price = current_price
                self._entry_cum_ret = cum_ret
        else:
            self._hold_count += 1
            stop_hit = False
            if self._entry_price and self._entry_price > 0:
                move = (current_price - self._entry_price) / self._entry_price
                stop_hit = (self._direction == "long" and move < -self.STOP_PCT) or \
                           (self._direction == "short" and move > self.STOP_PCT)
            # Exit: cum_ret crosses zero or max hold
            zero_cross = (self._direction == "long" and cum_ret > 0) or \
                         (self._direction == "short" and cum_ret < 0)
            if zero_cross or self._hold_count >= self.MAX_HOLD or stop_hit:
                signals.append(Signal(action="close", pair=pair, size_pct=1.0,
                                      order_type="market",
                                      rationale=f"exit hold={self._hold_count}"))
                self._direction = None
                self._hold_count = 0
                self._entry_price = None

        return signals
