"""Hypothesis: quant_primary_hyp_001_btc_4h_oscillation

Generated by agent quant_primary at cycle 2.
Config: {
  "hypothesis_id": "hyp_001_btc_4h_oscillation",
  "created_at": "2026-03-11T18:56:54.527886+00:00",
  "thesis": "BTC/USD 4h returns exhibit statistically meaningful negative autocorrelation at lags 8 (~32h), 14 (~56h), and 16 (~64h), with the lag-16 signal being strongest (-0.271). This implies that a sustained directional move over ~64 hours tends to partially reverse. A counter-trend strategy that fades extreme 64h moves should capture this oscillation pattern. Edge is in the entry signal itself \u2014 the reversal tendency \u2014 not just in risk management.",
  "strategy_type": "mean-reversion",
  "target_pairs": [
    "BTC/USD"
  ],
  "target_regimes": [
    "high_vol",
    "ranging"
  ],
  "signal_description": "Entry: When the cumulative 4h return over the past 16 candles (64h) exceeds +2 standard deviations of the 90-day rolling 64h-return distribution, go short. When it falls below -2 standard deviations, go long. Exit: When the 64h cumulative return reverts to within 0.5 standard deviations of zero, or after 8 candles (32h) maximum hold time, or if unrealized loss exceeds 3% of position value. Size: 20% of capital per signal. Order type: limit at close of signal candle.",
  "expected_trade_frequency": "2-4 trades per week",
  "expected_behavior": "Performs best in ranging/high-vol regimes where oscillation is pronounced. Will underperform in strong trending regimes where momentum overrides the reversion signal. Expected to be flat to slightly negative in trending bull markets.",
  "success_criteria": {
    "metric": "sharpe_ratio",
    "threshold": 0.8,
    "minimum_trade_count": 30,
    "evaluation_window": "90d backtest, then 14d paper",
    "robustness": {
      "random_entry_percentile_min": 85,
      "return_permutation_percentile_min": 70
    },
    "rationale": "Sharpe > 0.8 required because this strategy trades against momentum in a high-vol environment, incurring elevated risk. Minimum 30 trades needed to distinguish signal from luck at 90-day horizon. High random entry percentile (85th) required because the thesis is entirely about timing \u2014 if random entries match the strategy, the autocorrelation signal is carrying no real information. The entry signal must be doing the work."
  },
  "counterfactual_benchmark": {
    "description": "Simple BTC/USD buy-and-hold over the same period, and a naive 64h momentum strategy (go long when 64h return > 1 std, go short when < -1 std \u2014 trend-following version of the same signal)",
    "implementation": "Benchmark 1: hodl_btc (already tracked). Benchmark 2: Implement momentum version \u2014 enter long on +1std 64h move, short on -1std 64h move, same exit rules. If the mean-reversion version does not outperform the momentum version on Sharpe, the autocorrelation signal exists but is not exploitable in the direction I'm hypothesizing.",
    "null_hypothesis": "If the strategy Sharpe does not exceed 0.8 AND does not beat the 64h momentum version on Sharpe, the negative autocorrelation signal exists statistically but is not exploitable after costs, and the thesis is rejected."
  },
  "failure_modes": [
    "BTC enters a sustained trend (bull or bear) where 64h moves continue rather than reverting \u2014 strategy will accumulate losses on wrong-side positions",
    "Autocorrelation pattern is regime-specific and disappears during the backtest window",
    "Transaction costs and slippage eliminate the thin mean-reversion edge",
    "Ljung-Box significance test (when available) shows lags are not individually significant \u2014 the pattern is spurious",
    "Low trade count in backtest (<20) \u2014 insufficient to distinguish from random"
  ],
  "code_module": "strategies/backtest/quant_primary_hyp_001_btc_4h_oscillation.py"
}
"""

# TODO: Implement strategy module conforming to BaseStrategy interface.
