"""Hypothesis: quant_primary_hyp_001_btc_4h_oscillation

Generated by agent quant_primary at cycle 2.
Config: {
  "hypothesis_id": "hyp_001_btc_4h_oscillation",
  "created_at": "2026-03-11T18:56:54.527886+00:00",
  "thesis": "BTC/USD 4h returns exhibit statistically meaningful negative autocorrelation at lags 8 (~32h), 14 (~56h), and 16 (~64h), with the lag-16 signal being strongest (-0.271). This implies that a sustained directional move over ~64 hours tends to partially reverse. A counter-trend strategy that fades extreme 64h moves should capture this oscillation pattern. Edge is in the entry signal itself \u2014 the reversal tendency \u2014 not just in risk management.",
  "strategy_type": "mean-reversion",
  "target_pairs": [
    "BTC/USD"
  ],
  "target_regimes": [
    "high_vol",
    "ranging"
  ],
  "signal_description": "Entry: When the cumulative 4h return over the past 16 candles (64h) exceeds +2 standard deviations of the 90-day rolling 64h-return distribution, go short. When it falls below -2 standard deviations, go long. Exit: When the 64h cumulative return reverts to within 0.5 standard deviations of zero, or after 8 candles (32h) maximum hold time, or if unrealized loss exceeds 3% of position value. Size: 20% of capital per signal. Order type: limit at close of signal candle.",
  "expected_trade_frequency": "2-4 trades per week",
  "expected_behavior": "Performs best in ranging/high-vol regimes where oscillation is pronounced. Will underperform in strong trending regimes where momentum overrides the reversion signal. Expected to be flat to slightly negative in trending bull markets.",
  "success_criteria": {
    "metric": "sharpe_ratio",
    "threshold": 0.8,
    "minimum_trade_count": 30,
    "evaluation_window": "90d backtest, then 14d paper",
    "robustness": {
      "random_entry_percentile_min": 85,
      "return_permutation_percentile_min": 70
    },
    "rationale": "Sharpe > 0.8 required because this strategy trades against momentum in a high-vol environment, incurring elevated risk. Minimum 30 trades needed to distinguish signal from luck at 90-day horizon. High random entry percentile (85th) required because the thesis is entirely about timing \u2014 if random entries match the strategy, the autocorrelation signal is carrying no real information. The entry signal must be doing the work."
  },
  "counterfactual_benchmark": {
    "description": "Simple BTC/USD buy-and-hold over the same period, and a naive 64h momentum strategy (go long when 64h return > 1 std, go short when < -1 std \u2014 trend-following version of the same signal)",
    "implementation": "Benchmark 1: hodl_btc (already tracked). Benchmark 2: Implement momentum version \u2014 enter long on +1std 64h move, short on -1std 64h move, same exit rules. If the mean-reversion version does not outperform the momentum version on Sharpe, the autocorrelation signal exists but is not exploitable in the direction I'm hypothesizing.",
    "null_hypothesis": "If the strategy Sharpe does not exceed 0.8 AND does not beat the 64h momentum version on Sharpe, the negative autocorrelation signal exists statistically but is not exploitable after costs, and the thesis is rejected."
  },
  "failure_modes": [
    "BTC enters a sustained trend (bull or bear) where 64h moves continue rather than reverting \u2014 strategy will accumulate losses on wrong-side positions",
    "Autocorrelation pattern is regime-specific and disappears during the backtest window",
    "Transaction costs and slippage eliminate the thin mean-reversion edge",
    "Ljung-Box significance test (when available) shows lags are not individually significant \u2014 the pattern is spurious",
    "Low trade count in backtest (<20) \u2014 insufficient to distinguish from random"
  ],
  "code_module": "strategies/backtest/quant_primary_hyp_001_btc_4h_oscillation.py"
}
"""

import math

from strategies.base import BaseStrategy, Signal


class BTC4hOscillation(BaseStrategy):
    """Counter-trend strategy fading 64h BTC cumulative return extremes."""

    LOOKBACK = 16      # 16 x 4h = 64h window
    ROLLING = 30       # rolling periods for mean/std
    ENTRY_Z = 2.0
    EXIT_Z = 0.5
    MAX_HOLD = 8
    SIZE_PCT = 0.20
    STOP_PCT = 0.03

    def __init__(self, **kwargs):
        self._direction = None
        self._hold_count = 0
        self._entry_price = None

    def name(self) -> str:
        return "quant_primary_hyp_001_btc_4h_oscillation"

    def required_feeds(self) -> list[str]:
        return ["BTC/USD:4h"]

    def on_data(self, data: dict) -> list[Signal]:
        candles = data.get("candles_so_far", [])
        pair = data.get("pair", "BTC/USD")
        if len(candles) < self.LOOKBACK + self.ROLLING + 1:
            return []

        closes = [c["close"] for c in candles]
        cum_rets = [
            (closes[i] - closes[i - self.LOOKBACK]) / closes[i - self.LOOKBACK]
            for i in range(self.LOOKBACK, len(closes))
        ]
        if len(cum_rets) < self.ROLLING:
            return []

        window = cum_rets[-self.ROLLING:]
        mean = sum(window) / len(window)
        variance = sum((x - mean) ** 2 for x in window) / max(len(window) - 1, 1)
        std = math.sqrt(variance) if variance > 0 else 0.0
        if std == 0:
            return []

        z = (cum_rets[-1] - mean) / std
        current_price = closes[-1]
        signals = []

        if self._direction is None:
            if z < -self.ENTRY_Z:
                signals.append(Signal(action="buy", pair=pair, size_pct=self.SIZE_PCT,
                                      order_type="market", rationale=f"z={z:.2f}"))
                self._direction = "long"
                self._hold_count = 0
                self._entry_price = current_price
            elif z > self.ENTRY_Z:
                signals.append(Signal(action="sell", pair=pair, size_pct=self.SIZE_PCT,
                                      order_type="market", rationale=f"z={z:.2f}"))
                self._direction = "short"
                self._hold_count = 0
                self._entry_price = current_price
        else:
            self._hold_count += 1
            stop_hit = False
            if self._entry_price and self._entry_price > 0:
                move = (current_price - self._entry_price) / self._entry_price
                stop_hit = (self._direction == "long" and move < -self.STOP_PCT) or \
                           (self._direction == "short" and move > self.STOP_PCT)
            if abs(z) < self.EXIT_Z or self._hold_count >= self.MAX_HOLD or stop_hit:
                signals.append(Signal(action="close", pair=pair, size_pct=1.0,
                                      order_type="market",
                                      rationale=f"exit z={z:.2f} hold={self._hold_count}"))
                self._direction = None
                self._hold_count = 0
                self._entry_price = None

        return signals
