"""Hypothesis: quant_primary_hyp_001_ethbtc_pairs

Generated by agent quant_primary at cycle 3.
Config: {
  "hypothesis_id": "hyp_001_ethbtc_pairs",
  "created_at": "2026-03-11T20:59:06.986753+00:00",
  "thesis": "ETH and BTC are cointegrated at 4h timeframe with a stationary spread (hedge ratio ~0.0305). The spread mean-reverts with a half-life of ~7.7 periods (~1.3 days). When the spread deviates significantly from its rolling mean, a pairs trade (long ETH / short BTC or vice versa) should generate alpha as the spread reverts. The edge is structural cointegration, not momentum \u2014 this is a market-neutral, regime-independent strategy.",
  "strategy_type": "mean-reversion / stat-arb",
  "target_pairs": [
    "ETH/USD",
    "BTC/USD"
  ],
  "target_regimes": [
    "ranging",
    "high_vol",
    "trending_bull",
    "trending_bear"
  ],
  "signal_description": "Compute spread = ETH_price - (0.0305 \u00d7 BTC_price) - intercept. Track rolling 40-period (6.7 day) z-score of spread. Enter long ETH / short BTC when z-score < -1.5. Enter short ETH / long BTC when z-score > +1.5. Exit when z-score crosses zero. Use hedge ratio to size positions so that dollar exposure is balanced (market-neutral). Stop-loss at z-score \u00b13.5 (spread blowout / regime break).",
  "expected_trade_frequency": "2-4 round trips per week given 1.3-day half-life",
  "expected_behavior": "Market-neutral: should perform independently of BTC direction. In trending markets, the spread may drift before reverting \u2014 expect occasional drawdowns on individual legs. In ranging markets, faster convergence. In extreme events (correlation breakdown), potential for large losses \u2014 stop-loss at z=3.5 mitigates this.",
  "success_criteria": {
    "metric": "sharpe_ratio",
    "threshold": 1.0,
    "minimum_trade_count": 20,
    "evaluation_window": "90d backtest + 72h paper minimum",
    "robustness": {
      "random_entry_percentile_min": 75,
      "return_permutation_percentile_min": 70
    },
    "rationale": "Pairs trade alpha comes from the entry signal (spread z-score) but also significantly from risk management (exit at zero, stop at 3.5). Random entry threshold set at 75th percentile rather than 90th to reflect that exit logic carries real weight. Sharpe 1.0 is the minimum viable threshold for a strategy with this many moving parts. 20 trades minimum to distinguish edge from luck at 90d backtest. Note: with only 106 4h observations in the cointegration dataset, the backtest is statistically thin \u2014 paper trading results should be weighted heavily."
  },
  "counterfactual_benchmark": {
    "description": "Simple ETH/BTC ratio momentum: buy ETH when ETH/BTC ratio is below its 20-period moving average (ratio recovering), sell when above. This is the naive version of the cointegration insight \u2014 directional bet on ratio normalization without the market-neutral pairs structure.",
    "implementation": "Compute ETH/BTC ratio each 4h bar. If ratio < 20-period SMA, go long ETH (no BTC hedge). If ratio > 20-period SMA, go short ETH or hold cash. Size 50% of capital per signal.",
    "null_hypothesis": "If the pairs trade (market-neutral, z-score entry, hedge ratio exit) does not produce higher Sharpe than the simple ratio momentum strategy, then the complexity of the pairs structure is not adding value \u2014 the edge is just directional ETH/BTC mean reversion, which can be captured more simply."
  },
  "failure_modes": [
    "ETH/BTC structural regime shift \u2014 ratio continues declining without mean reversion (ETH loses relevance relative to BTC permanently)",
    "Correlation breakdown in a crisis event \u2014 both legs move directionally in the same direction, destroying market neutrality",
    "Spread half-life elongates beyond 5 days \u2014 the 1.3-day mean reversion assumption breaks, exits become slow and losses compound",
    "Data depth: with only 106 4h observations for cointegration estimation, hedge ratio may be noisy \u2014 backtest may overfit",
    "ADF p-value unknown (sir_011 pending) \u2014 cannot confirm spread stationarity with full statistical rigor"
  ],
  "code_module": "strategies/backtest/quant_primary_hyp_001_ethbtc_pairs.py"
}
"""

# TODO: Implement strategy module conforming to BaseStrategy interface.
