"""Hypothesis: quant_primary_hyp_001_ethbtc_statarb

Generated by agent quant_primary at cycle 1.
Config: {
  "hypothesis_id": "hyp_001_ethbtc_statarb",
  "created_at": "2026-03-11T21:10:56.862137+00:00",
  "thesis": "ETH and BTC are cointegrated with a hedge ratio of ~0.0306 and a mean-reversion half-life of ~1.3 days (7.67 x 4h periods). When the ETH/BTC spread deviates significantly from its mean, it reverts predictably. The edge is in the short-term mean reversion of this spread, not a directional view on either asset. Strategy goes long ETH / short BTC (or vice versa) when spread z-score exceeds \u00b11.5 standard deviations, targeting reversion to mean. Given high lag-1 autocorrelation (0.914), the spread is persistent enough to allow entries but fast enough to generate multiple trades per month.",
  "strategy_type": "mean-reversion",
  "target_pairs": [
    "ETH/USD",
    "BTC/USD"
  ],
  "target_regimes": [
    "ranging",
    "post_event",
    "high_vol"
  ],
  "signal_description": "Compute spread = ETH_price - 0.0306 * BTC_price - intercept. Normalize to z-score using 30-period (5-day) rolling mean and std. Enter long ETH / notional short BTC when z-score < -1.5. Enter short ETH / notional long BTC when z-score > +1.5. Exit when z-score crosses zero or after 3x half-life periods (4 days max hold). Size each leg at 15% of capital (30% gross exposure). On Kraken (spot only), implement as: when spread is low, buy ETH and reduce BTC; when spread is high, buy BTC and reduce ETH. Note: true pair trading requires simultaneous long/short \u2014 on spot-only exchange, implement as ETH overweight vs BTC underweight using relative sizing.",
  "expected_trade_frequency": "4-8 trades per month (half-life ~1.3 days implies frequent signal generation)",
  "expected_behavior": "Should produce uncorrelated returns vs BTC hodl. In trending bull markets, ETH/BTC spread may trend rather than revert \u2014 this is the primary failure mode. Strategy is designed for ranging or recovering regimes where relative value dominates directional momentum.",
  "success_criteria": {
    "metric": "sharpe_ratio",
    "threshold": 1.0,
    "minimum_trade_count": 20,
    "evaluation_window": "90d backtest, then 14d paper",
    "robustness": {
      "random_entry_percentile_min": 65,
      "return_permutation_percentile_min": 70
    },
    "rationale": "Lower random entry percentile (65) because entry signal (z-score threshold) should contribute but spread trading with tight half-life means exits also do heavy lifting. Permutation percentile 70 because we expect sequential dependency given persistent spread. Minimum 20 trades required \u2014 at 4-8/month over 90 days, expect 12-24 trades in backtest; fewer than 20 means signal is too sparse and results are unreliable."
  },
  "counterfactual_benchmark": {
    "description": "Simple ETH/BTC ratio momentum \u2014 buy whichever asset has stronger 5-day momentum, hold for 5 days",
    "implementation": "Every 5 days, compare ETH 5d return vs BTC 5d return. Allocate 30% to the stronger performer.",
    "null_hypothesis": "If the cointegration-based spread strategy does not outperform simple ETH/BTC momentum switching on Sharpe ratio, the spread signal adds no value beyond basic relative momentum."
  },
  "failure_modes": [
    "ETH/BTC ratio enters sustained trend (e.g., ETH re-rates structurally lower vs BTC) \u2014 cointegration breaks down",
    "Half-life shortens further, making spread revert before fills are executed",
    "Spot-only implementation creates execution asymmetry \u2014 can't simultaneously long/short",
    "During BTC directional moves >5% in 4h, both positions lose as correlation spikes to 1.0"
  ],
  "code_module": "strategies/backtest/primary_hyp_001_ethbtc_statarb.py"
}
"""

import math

from strategies.base import BaseStrategy, Signal


class ETHBTCStatArb(BaseStrategy):
    """ETH/BTC stat-arb approximated as single-leg ETH z-score mean reversion.

    Same thesis as ethbtc_pairs but with different parameters (30-period rolling,
    tighter entry). Hedge ratio 0.0306, half-life ~1.3 days.
    """

    ROLLING = 30       # 30 x 4h = 5 days
    ENTRY_Z = 1.5
    EXIT_Z = 0.0
    STOP_Z = 3.5
    MAX_HOLD = 20      # ~3x half-life periods (4 days)
    SIZE_PCT = 0.15

    def __init__(self, **kwargs):
        self._direction = None
        self._hold_count = 0

    def name(self) -> str:
        return "quant_primary_hyp_001_ethbtc_statarb"

    def required_feeds(self) -> list[str]:
        return ["ETH/USD:4h", "BTC/USD:4h"]

    def on_data(self, data: dict) -> list[Signal]:
        candles = data.get("candles_so_far", [])
        pair = data.get("pair", "ETH/USD")
        if len(candles) < self.ROLLING + 5:
            return []

        closes = [c["close"] for c in candles]
        window = closes[-self.ROLLING:]
        mean = sum(window) / len(window)
        variance = sum((x - mean) ** 2 for x in window) / max(len(window) - 1, 1)
        std = math.sqrt(variance) if variance > 0 else 0.0
        if std == 0:
            return []

        z = (closes[-1] - mean) / std
        signals = []

        if self._direction is None:
            if z < -self.ENTRY_Z:
                signals.append(Signal(action="buy", pair=pair, size_pct=self.SIZE_PCT,
                                      order_type="market", rationale=f"z={z:.2f}"))
                self._direction = "long"
                self._hold_count = 0
            elif z > self.ENTRY_Z:
                signals.append(Signal(action="sell", pair=pair, size_pct=self.SIZE_PCT,
                                      order_type="market", rationale=f"z={z:.2f}"))
                self._direction = "short"
                self._hold_count = 0
        else:
            self._hold_count += 1
            stop_hit = abs(z) > self.STOP_Z
            mean_cross = (self._direction == "long" and z >= self.EXIT_Z) or \
                         (self._direction == "short" and z <= self.EXIT_Z)
            if mean_cross or self._hold_count >= self.MAX_HOLD or stop_hit:
                signals.append(Signal(action="close", pair=pair, size_pct=1.0,
                                      order_type="market",
                                      rationale=f"exit z={z:.2f}"))
                self._direction = None
                self._hold_count = 0

        return signals
